### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by Glanceman**
Change to 2Dvector

### CODE REVIEW

**Review by SmallHotDogBun — COMMENTED** [review]
still working

**Comment by Zhibin-Chen-017** [comment]
char数组没有进行填充，导致调用iswin函数会出现错误

**Comment by Ahuans** [comment]
> char数组没有进行填充，导致调用iswin函数会出现错误
 
i have found the question you point out, i will try my best to solve this problem

**Comment by Zhibin-Chen-017** [comment]
don't need to use  "using namespace std;"

**Comment by Ahuans** [comment]
> don't need to use "using namespace std;"

i got it, i will delete this term

**Pull request merged**
